# Generated by Django 3.2.9 on 2022-12-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=12)),
            ],
        ),
    ]
