# Generated by Django 3.2.9 on 2022-12-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='email',
            field=models.CharField(max_length=27),
        ),
    ]
